FROM nvcr.io/nvidia/driver:525.85.12-ubuntu22.04

LABEL image.authors="Lucas Tan"
LABEL image.description="PyTorch 2.0.0 with CUDA 11.7"
LABEL authors.email="lucas.y.tan.life@outlook.com"

# 换源
RUN sed -i 's/archive.ubuntu.com/mirrors.cqu.edu.cn/g' /etc/apt/sources.list \
    && apt update -y \
    && apt upgrade -y \
    && apt install vim -y \
    && apt install wget -y \
    && apt install python3 -y \
    && apt install python3-pip -y \
    && mkdir -p ~/.pip/ \
    && touch ~/.pip/pip.conf \
    && echo "[global]" >> ~/.pip/pip.conf \
    && echo "index-url = https://mirrors.cqu.edu.cn/pypi/web/simple" >> ~/.pip/pip.conf
    # && pip config set global.index-url https://mirrors.cqu.edu.cn/pypi/web/simple

RUN alias pip=pip3 \
    && alias python=python3 \
    && pip install numpy --pre torch torchvision torchaudio --force-reinstall --index-url https://download.pytorch.org/whl/nightly/cu118

VOLUME [ "/root/share" ]

EXPOSE 8888

# CMD echo $HOME
