# 注意：先参考README配置NVIDIA Container Toolkit
FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel

# 换源
RUN sed -i 's/archive.ubuntu.com/mirrors.cqu.edu.cn/g' /etc/apt/sources.list \
    && apt update -y \
    && apt upgrade -y \
    && apt install vim -y \
    && apt install wget -y \
    && apt install python -y \
    && apt install python3-pip -y \
    && mkdir -p ~/.pip \
    && touch ~/.pip/pip.conf \
    && echo "[global]" >> ~/.pip/pip.conf \
    && echo "index-url = https://mirrors.cqu.edu.cn/pypi/web/simple" >> ~/.pip/pip.conf
    # && pip config set global.index-url https://mirrors.cqu.edu.cn/pypi/web/simple

# RUN conda init bash \
#     && source ~/.bashrc

VOLUME [ "/workspace" ]

EXPOSE 8888

# 不要加这个，运行完主进程镜像就会结束退出
# CMD echo $HOME
